### ISSUE TITLE
Hamburger menu always shows Pipeline Design sub-menu initially

### ISSUE THREAD

**Issue by noizwaves** [pivotal/docs-platform-automation#11]
**Describe the bug**
When looking at a page, the hamburger menu does not "focus" on where the page is in the menu hierarchy. This confused me initially when exploring the breadth of the documentation.

**To Reproduce**
1. In Chrome, navigate to https://docs-platform-automation.cfapps.io/platform-automation/v2.1/reference/task.html
2. Click on the hamburger menu icon
3. Menu shows the "Pipeline Design" sub-menu

**Expected behavior**
Expected to see the "References" sub-menu shown

**Screenshots**
<img width="1552" alt="actual behaviour" src="https://user-images.githubusercontent.com/1007983/53902733-113e0b80-3fff-11e9-8908-44808b2f8fa0.png">

**Desktop (please complete the following information):**
 - MacOS 10.14.3
 - Chrome 72.0.3626.121

**Additional context**
Even more confusing, pressing the back button located in the menu itself does not traverse up the menu hierarchy to the root. Instead, it traverses linearly back through the sibling sub-menus.

**Comment by jtarchie** [comment]
Notes to self: This appears to be an issue with the expanded left hand side nav. Using the base `mkdocs-material` we forced the subsections always to be expanded in a wide view mode. When the *hamburger* appears, the expansion of all the subsections is what is causing the layers on layers of navigation.

**Comment by kcboyle** [comment]
This should be fixed in the next release of platform automation 2.2.0

**Comment by noizwaves** [comment]
Awesome, thank you! 🙂

**Comment by jtarchie** [comment]
This has been released!
