### ISSUE TITLE
Add quotes to fly command in Install Operations Manager example

### ISSUE THREAD

**Issue by bottkars** [pivotal/docs-platform-automation#12]
**URL or GitHub link to the page where you're having the issue**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

**Is your request for a change or addition to content related to a problem? If so, please describe.**
A clear and concise description of the problem. For example: "Whenever I upgrade my software I forget to first collect information about the things I've already installed"

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or content you've considered.

**Additional context**
Add any other context or screenshots about the content request here.

`
# note the space before the command
 fly -t control-plane set-pipeline \
     -p foundation \
     -c pipeline.yml \
     -v pivnet-refresh-token=your-api-token`

needs tom have content of -v in double quotes:

# note the space before the command
 fly -t control-plane set-pipeline \
     -p foundation \
     -c pipeline.yml \
     -v "pivnet-refresh-token=your-api-token"

**Comment by jtarchie** [comment]
The quotes are only required if a space in the value.

**Comment by kcboyle** [comment]
@jtarchie are quotes required if there is a special character (other than a space?)

**Comment by bottkars** [comment]
I encountered some issues when not. However, I suspect now it was a slow response of my controlplane ?!


Von meinem iPhone gesendet

Am 28.05.2019 um 18:12 schrieb Kira Combs Boyle <notifications@github.com<mailto:notifications@github.com>>:


@jtarchie<https://github.com/jtarchie> are quotes required if there is a special character (other than a space?)

**Comment by jtarchie** [comment]
Can you clarify what you mean by a slow response?
The error originally reported was due to command line arguments, right?

**Comment by ccattin** [comment]
Closing based on inactivity, please feel free to reopen.
