### ISSUE TITLE
download product "put" to save to S3

### ISSUE THREAD

**Issue by Houlistonm** [pivotal/docs-platform-automation#17]
The following section in the documentation ....
'''
download-product

Downloads a product specified in a config file from an S3-compatible blobstore. This is useful when retrieving assets in an offline environment.

Downloads are cached, so files are not re-downloaded each time.

This is intended to be used with files downloaded from Pivnet by download-product and then persisted to a blobstore using a put step.
'''

Please provide an example of a "put" to store to S3.

As far as I can discern from the code, the write to S3 is a function of the config.yaml that is passed to the download-product task and NOT from a put directive.

 I'd like to see some clear examples of download-product (and stemcells) that store to S3 for future download from s3. (air-gapped environment).

The documentation should include some clear examples for customers in an air-gapped environment (no direct connection to pivnet).

**Comment by nbconklin** [comment]
Thanks for this report. We do have an offline workflow for reference in our Reference Pipelines section that will be helpful for you. However, we do want to make this more clear in our docs and have revised this request to include showcasing an offline workflow in our documentation.
