### ISSUE TITLE
Reference Pipeline uses git state resource but doesn't define the resource anywhere

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal/docs-platform-automation#22]
**URL or GitHub link to the page where you're having the issue**

https://docs.pivotal.io/platform-automation/v4.0/pipelines/single-product.html#configured-resources

**Is your request for a change or addition to content related to a problem? If so, please describe.**

In v4 of the reference pipeline for Ops Manager + a product https://docs.pivotal.io/platform-automation/v4.0/pipelines/single-product.html#configured-resources the `variable` state store was renamed to `state` and the resource definition was removed. You can see how it was defined in v3 here: https://docs.pivotal.io/platform-automation/v3.0/pipeline/single-product.html#configured-resources . The reference pipeline now calls this resource `state` but the user of the documentation is unaware that it is a git resource because the resource definition was removed. 

**Describe the solution you'd like**

Add the definition for the state resource back:

```
- name: state
  type: git
  source:
    private_key: ((state.private_key))
    uri: ((state.uri))
    branch: master
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jtarchie** [comment]
Thanks for letting us know. We'll add that in shortly.

**Comment by jtarchie** [comment]
We've added this back in the 4.0 branches of the docs.
The 3.0 docs relied on using the `configuration` git repo to persist the state file.
This means the resource is already defined.
