### ISSUE TITLE
hostname is DEPRECATED

### ISSUE THREAD

**Issue by chenweienn** [pivotal/docs-platform-automation#24]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/platform-automation/v4.1/inputs-outputs.html#vsphere
https://github.com/pivotal/docs-platform-automation/blob/v4.1/docs/examples/opsman-config/vsphere.yml

**Is your request for a change or addition to content related to a problem? If so, please describe.**
hostname is DEPRECATED:
https://github.com/pivotal/platform-automation/blob/5a31a5a4ca1bdbc15d9a3e2ea941e281acfaab4b/pkg/vmmanagers/vsphere.go#L113

**Describe the solution you'd like**
We should modify the example to reflect the DEPRECATION of hostname.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jtarchie** [comment]
Thanks for pointing this out.
We documented the correct field, but the message from the CLI was for the incorrect field.
We have corrected this and it will be out in the next release of the respective 4.1.x and 4.2.x lines.
