### ISSUE TITLE
Dot instead dash

### ISSUE THREAD

**Issue by SergeyMuha** [pivotal/docs-platform-automation#25]
**URL or GitHub link to the page where you're having the issue**
https://github.com/pivotal/docs-platform-automation/blob/d3d106144126108e197f0aa7859c477b0eddb5b6/docs/examples/pipeline/pks/pipeline.yml

  - name: platform-automation-tasks
    type: s3
    source:
      access_key_id: ((s3.access_key_id))
      secret_access_key: ((s3.secret_access_key))
      region_name: ((s3.region_name))
      bucket: ((s3.buckets.pivnet_products))
      regexp: .*tasks-(.*).zip

  - name: platform-automation-image
    type: s3
    source:
      access_key_id: ((s3.access_key_id))
      secret_access_key: ((s3.secret_access_key))
      region_name: ((s3.region_name))
      bucket: ((s3.buckets.pivnet_products))
      regexp: .*image-(.*).tgz

 these examples with dot but should have _
 like here
  - name: telemetry-collector-binary
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      bucket: ((s3_pivnet_products_bucket))
      regexp: .*telemetry-(.*).tgz

**Comment by nbconklin** [comment]
Thanks for notifying us, we've updated this in the documentation.
