### ISSUE TITLE
Unify recommendations for folder layouts

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal/docs-platform-automation#26]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/platform-automation/v4.3/how-to-guides/git-repo-layout.html https://docs.pivotal.io/platform-automation/v4.3/pipeline-design/configuration-management-strategies.html 

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Each of these links has a recommendation for how to layout the configuration and they differ. 

**Describe the solution you'd like**
It would be less confusing to a user if the recommendations where the same or pointed to the same page. 

**Describe alternatives you've considered**

**Additional context**

**Comment by kcboyle** [comment]
Hi @patrick-huber-pivotal ! Wanted to let you know that we are indeed working on this issue. We took a step back even further than this issue, and wanted to take a look at what repo structure we recommend period. We are exploring multi-foundation repo structure recommendations at the moment, and are making good progress. 

Once we have them figured out, we will go back and edit these pages accordingly. We have identified two strategies that are very similar, but differ slightly in some places in regards to how you set it up and how files are moved around/updated between versions. This difference is whether configuration is managed via `om config-template` or `om staged-config`.

Currently, the `om staged-config` strategy has a tested structure in the [docs-platform-automation-reference-pipeline-config](https://github.com/pivotal/docs-platform-automation-reference-pipeline-config/tree/single-product) repo. We're still exploring how best to document the process and make this repo more discoverable from docs.

**Comment by kcboyle** [comment]
Hi @patrick-huber-pivotal ! We are adding some docs for this that will be released in Platform Automation 5.0.0. You can view them early on the [`develop` branch](https://docs.pivotal.io/platform-automation/develop/pipeline-design/configuration-management-strategies.html#multiple-foundations-with-one-repository) of the docs. Feedback always welcome!
