### ISSUE TITLE
upgrade-opsman state.yml comments don't include usage of $timestamp for non-versioned s3 files

### ISSUE THREAD

**Issue by bridgetarthur** [pivotal/docs-platform-automation#27]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/platform-automation/v4.3/tasks.html#upgrade-opsman

**Is your request for a change or addition to content related to a problem? If so, please describe.**
It wasn't clear how to utilize `$timestamp` for non-versioned s3 state.yml files, but we were able to find the solution looking at the comments in delete-vm

**Describe the solution you'd like**
Add similar text from delete-vm to upgrade-opsman i.e
``` STATE_FILE: state.yml
  # - Required
  # - Filepath of the state yaml file
  # - The path is relative to root of the `state` output
  # - if the filename includes "$timestamp",
  #   for example "state-$timestamp.yml",
  #   the final filename will include the current timestamp.
  #   - this is necessary if using an "S3 compatible" blobstore
  #     that doesn't support versioned blobs
  #   - timestamped filenames will need to be represented
  #     with a glob-style wildcard in tasks that use this state file
  #     (such as state-*.yml)
```

**Comment by kcboyle** [comment]
This should be updated both in staging and production docs. Thanks for bringing this to our attention!
