### ISSUE TITLE
Reference Pipeline will not correctly report healthwatch metrics

### ISSUE THREAD

**Issue by kcboyle** [pivotal/docs-platform-automation#34]
**URL or GitHub link to the page where you're having the issue**
The [reference pipeline](https://github.com/pivotal/docs-platform-automation-reference-pipeline-config)

Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 
Same as above. The future issue will be related to the Healthwatch install in the pipeline.

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Both a change and an addition. The reference pipeline installs TAS, TKGI, and Healthwatch. 

When Healthwatch 2.1 is released as GA (coming soon in March 2021), this will no longer be enough. Healthwatch 2.1 requires the install of Exporter tiles (one for TKGI, one for TAS) in order to report metrics on those installed tiles. 

**Describe the solution you'd like**
update the reference pipeline and/or how-to guides to include the install of the exporter tiles when installing Healthwatch 2.1. 

**Describe alternatives you've considered**
- only install one exporter (this may be required anyway, I am not sure)
- make a warning/note that HW 2.1+ will not display metrics properly without the exporter tiles (not included) installed.

**Additional context**
- If you want to test that this update works, you can request for access(if it's not already available) to the (currently) beta tile in #pcf-healthwatch channel.

**Comment by kcboyle** [comment]
I was able to validate that both exporters can be installed (in the case of an environment with TAS and TKGI installed
HW2+ is GA! 
HW1 is EOGS 2021-10-30

**Comment by jaristiz** [comment]
Hi @kcboyle ,

Thanks for your update, we are going to take a look at this issue, and plan some work.

Regards,

**Comment by jaristiz** [comment]
An update on this issue, we just finished making changes to support Healtwatch 2.1.5 and the configuration of both exporters, changes can be seen on the  [reference-pipeline](https://github.com/pivotal/docs-platform-automation-reference-pipeline-config)
